### ISSUE TITLE
Unsubscribing from a channel can be tough.

### ISSUE THREAD

**Issue by Ben-Fenner** [own3mall/YouTubeNonStop-Legacy-XUL-Extension#3]
I'm back with another ticket!

Luckily this one is easily reproducable.

Head over to any YouTube channel's `About` page. (For example: https://www.youtube.com/@mattmoto/about )
Make sure you are subscribed to whatever channel it is.
Attempt to Unsubscribe from the channel using the convenient button.
A confirmation box will appear, and then disappear within 5 seconds.

Of course if you confirm fast enough, things work as expected. No doubt this is another window/modal/popup that is collateral damage from this extension. Let me know if I need to provide any more details.

Cheers!

**Comment by own3mall** [comment]
@Ben-Fenner , can you please try this version:

https://github.com/own3mall/YouTubeNonStop-Legacy-XUL-Extension/raw/master/release/YouTubeNonStop.xpi

Let me know how it goes and that everything still works properly.  :+1:

**Comment by Ben-Fenner** [comment]
Okay, will do. Give me a few days to report back.

**Comment by Ben-Fenner** [comment]
Sorry for the delay, I've just installed it (4 days after posting above) so will report back soon.

Unsbscribing from a channel works well again, thank you. I still will give it a few days of usage to make sure everything else seems good and report back.

**Comment by Ben-Fenner** [comment]
@own3mall I have been stressing the tool as best I can and all seems good. I'd say you're clear to release to production from my end. :+1:

**Comment by own3mall** [comment]
@Ben-Fenner thanks!
